// <auto-generated />
namespace SCINOLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migr97 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migr97));
        
        string IMigrationMetadata.Id
        {
            get { return "201508261057223_migr97"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
